### ISSUE TITLE
Keep URL argument when not logged in

### ISSUE THREAD

**Issue by vmario89** [sismics/docs#472]
Hi,
sometimes i get a DMS url to open a document. But if i am not logged in i have to enter credentials first. Clicking the login button i am on the front page again so i have to open the initial link twice to show it. It would be cool if Teedy could remember the URL which was provided before, to continue opening that document directly after login. For my use case a share URL does not make sense

**Comment by Vec7or** [comment]
@vmario89 I have implemented the functionality described. Could you have a look and tell me if it works as you expected? The build is available as `vec7or/docs:1.0.0`.

**Comment by Vec7or** [comment]
Please reopen since this is not finished yet.

**Comment by jendib** [comment]
Is it? I tested it and it was all good.

**Comment by vmario89** [comment]
Hey @jendib and @Vec7or . I tested this but the same thing still happens, like described in https://github.com/sismics/docs/pull/491#issuecomment-754542034

regards, Mario

**Comment by Vec7or** [comment]
Hey @vmario89 could you create a new issue regarding this problem? I will try to work this out as soon as I have some time to spare. I am currently a little busy so this may take some time.

**Comment by vmario89** [comment]
hey. please just reopen this issue if possible

**Comment by jendib** [comment]
Do you still have an error log on the server? I think it's not related to this issue honestly.

**Comment by vmario89** [comment]
Hi. sorry for late reply. No the log output seems fine. no bad errors to see. Its the just issue with the infite loading spinner icon
